# fly.toml app configuration file generated for wannachat on 2024-10-21T11:52:37+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wannachat'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
  [[http_service.ports]]
    handlers = ["http", "tls", "ws"]  # Add "ws" for WebSocket support
    port = 443  # Standard HTTPS port for secure WebSocket connections

  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
